[tool.poetry]
name = "training-template"
version = "0.1.0"
description = ""
authors = ["sunny joshi <sankrantijoshi14@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
