name: Pull updates from template repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper merging

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add template remote and fetch
        run: |
          git remote add template https://github.com/sunny1401/training_template.git
          git fetch template main

      - name: Create update branch and merge template
        run: |
          git checkout -b update-from-template
          git merge template/main --allow-unrelated-histories || true
          git add -A || true
          git commit -m "Merge updates from template repo" || true

      - name: Push update branch
        run: git push origin update-from-template --force
